name: 'jest coverage'
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'e2e-tests/**'
    types: [opened, synchronize, reopened]
jobs:
  jest-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: 'failed-tests'
